### PR TITLE
#ATM-WEB Add mailchimp configuration guide for losses calculator

### PR DESCRIPTION
**Pull request by jelaucv**

### CODE REVIEW

**Comment by jelaucv** [comment]
Updated backend calculator endpoint, please take care and test losses calculator functionality.

**Comment by AlexandrUrita** [comment]
New dev build received for QA on 07.07.2017

**Comment by AlexandrUrita** [comment]
New build for QA was received on 07.07.2017 (d3qpdk1g0ojf0w.cloudfront.net)

**Comment by veronicamacovei** [comment]
`Test Passed`
**Function:**                                   
total_pageviews × 30%=X
X × total_ads=Y
Y × %CRT(industry)=Z
Z × CPC(industry)=Final result

_Example for E-Commerce industry_ 
- total_page_views=100000, total_ads=3, CRT=0.45%, CPC=0.1972$
100000 × 30%=30000
30000 × 3=90000
90000 × 0,45%=405
405 × 0.1972$=79,87$

Result from UI:
screen shot 2017-07-07 at 4 38 51 pm

screen shot 2017-07-07 at 4 39 25 pm

screen shot 2017-07-07 at 4 41 31 pm

**Pull request merged**
