### PR TITLE
Enable chai

### PR DESCRIPTION
**Pull request by eistrati**

### CODE REVIEW

**Review by ddimitrioglo — APPROVED** [review]

**Comment by eistrati** [comment]
#13 finished with SUCCESS

**Comment by eistrati** [comment]
#14 finished with SUCCESS

**Comment by eistrati** [comment]
#35 finished with FAILURE

**Comment by eistrati** [comment]
Testing

**Comment by ddimitrioglo** [comment]
@eistrati i have other thoughts about this implementation, as soon as we finish with urgent tasks on recink, I'll refactor this immediately

**Pull request closed without merging**
